build:
    # The build contains everything related to running test, deployment and analysis commands.
    services:
        mariadb: 10

    dependencies:
        override:
            - true     # do not install any dependencies
    tests:
        override:
            - ~/build/tests/setup/run-tests.sh

    nodes:
        code-analysis-and-test-mw-master:
            environment:
                php: 7.3
                variables:
                    MW: master
                    SBU: composer
            tests:
                override:
                    -   command: ~/build/tests/setup/run-tests.sh --coverage-clover ~/coverage.xml
                        coverage:
                            file: ~/coverage.xml
                            format: clover
                    -   command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run --enable-security-analysis
        test-mw-min-version:
            environment:
                php: 7.0
                variables:
                    MW: 1.31.0
                    SBU: download
        test-mw-1.31:
            environment:
                php: 7.1
                variables:
                    MW: 1.31.3
                    SBU: composer
        test-mw-1.32:
            environment:
                php: 7.2
                variables:
                    MW: 1.32.3
                    SBU: download
        test-mw-1.33:
            environment:
                php: 7.2
                variables:
                    MW: 1.33.0
                    SBU: download

filter:
# The filter section defines which files are analyzed, where dependencies are located and which files should be completely ignored.
    dependency_paths:
        - mw
    excluded_paths:
        - mw/extensions

build_failure_conditions: {}
# The build failure conditions section allows you to define failure conditions where a build should be failed based on findings in the analysis.
# Findings can be that code coverage has decreased below a certain point, or that new issues have been found, etc.
